# Generated by Django 4.2.6 on 2023-11-16 17:54

from django.db import migrations
import django_enum_choices.choice_builders
import django_enum_choices.fields
import s3.models


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s3list',
            name='check_name',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[("('s3_check_public_access_block', <IMPORTANCE.HIGH: 0>, '주의 사항')", "('s3_check_public_access_block', <IMPORTANCE.HIGH: 0>, '주의 사항')"), ("('s3_check_bucket_public_access', <IMPORTANCE.HIGH: 0>, '주의 사항')", "('s3_check_bucket_public_access', <IMPORTANCE.HIGH: 0>, '주의 사항')"), ("('s3_check_account_level_public_access_block', <IMPORTANCE.MID: 1>, '주의 사항')", "('s3_check_account_level_public_access_block', <IMPORTANCE.MID: 1>, '주의 사항')"), ("('s3_check_bucket_use_acl', <IMPORTANCE.HIGH: 0>, '주의 사항')", "('s3_check_bucket_use_acl', <IMPORTANCE.HIGH: 0>, '주의 사항')"), ("('s3_check_bucket_encryption', <IMPORTANCE.MID: 1>, '주의 사항')", "('s3_check_bucket_encryption', <IMPORTANCE.MID: 1>, '주의 사항')"), ("('s3_check_bucket_mfa_delete', <IMPORTANCE.MID: 1>, '주의 사항')", "('s3_check_bucket_mfa_delete', <IMPORTANCE.MID: 1>, '주의 사항')"), ("('s3_check_bucket_object_lock', <IMPORTANCE.HIGH: 0>, 'S3 버킷 객체 잠금이 활성화되어 있습니다.')", "('s3_check_bucket_object_lock', <IMPORTANCE.HIGH: 0>, 'S3 버킷 객체 잠금이 활성화되어 있습니다.')"), ("('s3_check_bucket_policy', <IMPORTANCE.MID: 1>, 'S3 버킷 버킷 정책이 없습니다.')", "('s3_check_bucket_policy', <IMPORTANCE.MID: 1>, 'S3 버킷 버킷 정책이 없습니다.')"), ("('s3_check_bucket_secure_transport_policy', <IMPORTANCE.MID: 1>, 'S3 버킷 안전한 전송 정책이 있습니다.')", "('s3_check_bucket_secure_transport_policy', <IMPORTANCE.MID: 1>, 'S3 버킷 안전한 전송 정책이 있습니다.')"), ("('s3_check_ssl_endpoint', <IMPORTANCE.MID: 1>, 'S3 버킷 S3 SSL 엔드포인트를 사용하여 HTTPS를 통해 데이터를 전송할 수 있습니다.')", "('s3_check_ssl_endpoint', <IMPORTANCE.MID: 1>, 'S3 버킷 S3 SSL 엔드포인트를 사용하여 HTTPS를 통해 데이터를 전송할 수 있습니다.')"), ("('s3_check_server_side_encryption', <IMPORTANCE.MID: 1>, 'S3 버킷 x-amz-server-side-encryption(서버 측 암호화) 헤더가 포함되지 않는 경우, 객체 업로드 (S3:PutObject) 권한을 거부하고 있습니다.')", "('s3_check_server_side_encryption', <IMPORTANCE.MID: 1>, 'S3 버킷 x-amz-server-side-encryption(서버 측 암호화) 헤더가 포함되지 않는 경우, 객체 업로드 (S3:PutObject) 권한을 거부하고 있습니다.')"), ("('s3_check_bucket_versioning', <IMPORTANCE.MID: 1>, 'S3 버킷 버킷에 저장된 모든 객체 보존 및 복원이 (자동화) 되어 있습니다.')", "('s3_check_bucket_versioning', <IMPORTANCE.MID: 1>, 'S3 버킷 버킷에 저장된 모든 객체 보존 및 복원이 (자동화) 되어 있습니다.')"), ("('s3_check_bucket_acl', <IMPORTANCE.MID: 1>, 'S3 버킷 모든 S3 계정 수준에서 접근이 금지되어 있습니다.')", "('s3_check_bucket_acl', <IMPORTANCE.MID: 1>, 'S3 버킷 모든 S3 계정 수준에서 접근이 금지되어 있습니다.')")], enum_class=s3.models.S3Enum, max_length=157),
        ),
    ]
