# Generated by Django 4.2.6 on 2023-11-13 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_enum_choices.choice_builders
import django_enum_choices.fields
import django_enumfield.db.fields
import vpc.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vpc',
            fields=[
                ('vpc_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('last_modified', models.DateTimeField()),
                ('passed_num', models.IntegerField()),
                ('total_num', models.IntegerField()),
                ('root_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vpc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VpcList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_name', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('vpc_check_flow_logs', 'vpc_check_flow_logs'), ('vpc_check_endpoint_permissions', 'vpc_check_endpoint_permissions'), ('vpc_check_endpoint_trusted_account_with_arn', 'vpc_check_endpoint_trusted_account_with_arn'), ('vpc_check_endpoint_with_two_account_ids_one_trusted_one_not', 'vpc_check_endpoint_with_two_account_ids_one_trusted_one_not'), ('vpc_check_routing_table_peering', 'vpc_check_routing_table_peering'), ('vpc_check_subnets', 'vpc_check_subnets'), ('vpc_check_subnet_availability_zone', 'vpc_check_subnet_availability_zone'), ('elbv2_check_logging_enabled', 'elbv2_check_logging_enabled')], enum_class=vpc.models.VpcEnum, max_length=59)),
                ('check_code', models.CharField(max_length=255)),
                ('importance', django_enumfield.db.fields.EnumField(default=1, enum=vpc.models.IMPORTANCE)),
                ('status', models.BooleanField()),
                ('pass_line', models.TextField()),
                ('check_point', models.TextField()),
                ('modified_date', models.DateTimeField()),
                ('root_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpc_list_records', to=settings.AUTH_USER_MODEL)),
                ('vpc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpc_list_entries', to='vpc.vpc')),
            ],
        ),
    ]
