# Generated by Django 4.2.6 on 2023-10-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('root_id', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('access_key', models.CharField(default='None', max_length=200)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
