# Generated by Django 4.2.6 on 2023-11-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aws_region',
            field=models.CharField(choices=[('us-east-1', '미국 동부(버지니아 북부)'), ('us-east-2', '미국 동부(오하이오)'), ('us-west-1', '미국 서부(캘리포니아 북부)'), ('us-west-2', '미국 서부(오리건)'), ('af-south-1', '아프리카(케이프타운)'), ('ap-east-1', '아시아 태평양(홍콩)'), ('ap-south-2', '아시아 태평양(하이데라바드)'), ('ap-southeast-3', '아시아 태평양(자카르타)'), ('ap-southeast-4', '아시아 태평양(멜버른)'), ('ap-south-1', '아시아 태평양(뭄바이)'), ('ap-northeast-3', '아시아 태평양(오사카)'), ('ap-northeast-2', '아시아 태평양(서울)'), ('ap-southeast-1', '아시아 태평양(싱가포르)'), ('ap-southeast-2', '아시아 태평양(시드니)'), ('ap-northeast-1', '아시아 태평양(도쿄)'), ('ca-central-1', '캐나다(중부)'), ('eu-central-1', '유럽(프랑크푸르트)'), ('eu-west-1', '유럽(아일랜드)'), ('eu-west-2', '유럽(런던)'), ('eu-south-1', '유럽(밀라노)'), ('eu-west-3', '유럽(파리)'), ('eu-south-2', '유럽(스페인)'), ('eu-north-1', '유럽(스톡홀름)'), ('eu-central-2', '유럽(취리히)'), ('il-central-1', '이스라엘(텔아비브)'), ('me-south-1', '중동(바레인)'), ('me-central-1', '중동(UAE)'), ('sa-east-1', '남아메리카(상파울루)')], default='ap-northeast-2', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='key_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='access_key',
            field=models.CharField(default='', max_length=200),
        ),
    ]
