# Generated by Django 4.2.6 on 2023-11-13 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_enum_choices.choice_builders
import django_enum_choices.fields
import django_enumfield.db.fields
import ec2.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ec2',
            fields=[
                ('ec2_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('last_modified', models.DateTimeField()),
                ('passed_num', models.IntegerField()),
                ('total_num', models.IntegerField()),
                ('root_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ec2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ec2List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_name', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('ec2_ami_public', 'ec2_ami_public'), ('ec2_ebs_default_encryption', 'ec2_ebs_default_encryption'), ('ec2_ebs_public_snapshot', 'ec2_ebs_public_snapshot'), ('ec2_ebs_snapshots_encrypted', 'ec2_ebs_snapshots_encrypted'), ('ec2_ebs_volume_encryption', 'ec2_ebs_volume_encryption'), ('ec2_elastic_ip_shodan', 'ec2_elastic_ip_shodan'), ('ec2_elastic_ip_unassgined', 'ec2_elastic_ip_unassgined'), ('ec2_instance_detailed_monitoring_enabled', 'ec2_instance_detailed_monitoring_enabled'), ('ec2_instance_imdsv2_enabled', 'ec2_instance_imdsv2_enabled'), ('ec2_instance_internet_facing_with_instance_profile', 'ec2_instance_internet_facing_with_instance_profile'), ('ec2_instance_managed_by_ssm', 'ec2_instance_managed_by_ssm'), ('ec2_instance_older_than_specific_days', 'ec2_instance_older_than_specific_days'), ('ec2_instance_profile_attached', 'ec2_instance_profile_attached'), ('ec2_instance_public_ip', 'ec2_instance_public_ip'), ('ec2_instance_secrets_user_data', 'ec2_instance_secrets_user_data'), ('ec2_networkacl_allow_ingress_tcp_port_22', 'ec2_networkacl_allow_ingress_tcp_port_22'), ('ec2_securitygroup_allow_ingress_from_internet_to_tcp_ftp_port_20_21', 'ec2_securitygroup_allow_ingress_from_internet_to_tcp_ftp_port_20_21'), ('ec2_securitygroup_allow_ingress_from_internet_to_tcp_port_mysql', 'ec2_securitygroup_allow_ingress_from_internet_to_tcp_port_mysql'), ('ec2_securitygroup_allow_wide_open_public_ipv4', 'ec2_securitygroup_allow_wide_open_public_ipv4'), ('ec2_securitygroup_default_restrict_traffic', 'ec2_securitygroup_default_restrict_traffic'), ('ec2_securitygroup_not_used', 'ec2_securitygroup_not_used')], enum_class=ec2.models.EC2ENUM, max_length=67)),
                ('check_code', models.CharField(max_length=255)),
                ('importance', django_enumfield.db.fields.EnumField(default=1, enum=ec2.models.IMPORTANCE)),
                ('status', models.BooleanField()),
                ('pass_line', models.TextField()),
                ('check_point', models.TextField()),
                ('modified_date', models.DateTimeField()),
                ('ec2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ec2_list_entries', to='ec2.ec2')),
                ('root_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ec2_list_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
