# Generated by Django 4.2.6 on 2023-11-16 08:18

from django.db import migrations
import django_enum_choices.choice_builders
import django_enum_choices.fields
import ec2.models


class Migration(migrations.Migration):

    dependencies = [
        ('ec2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ec2list',
            name='check_name',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('ec2_ami_public', 'ec2_ami_public'), ('ec2_ebs_default_encryption', 'ec2_ebs_default_encryption'), ('ec2_ebs_public_snapshot', 'ec2_ebs_public_snapshot'), ('ec2_ebs_snapshots_encrypted', 'ec2_ebs_snapshots_encrypted'), ('ec2_ebs_volume_encryption', 'ec2_ebs_volume_encryption'), ('ec2_elastic_ip_shodan', 'ec2_elastic_ip_shodan'), ('ec2_elastic_ip_unassgined', 'ec2_elastic_ip_unassgined'), ('ec2_instance_detailed_monitoring_enabled', 'ec2_instance_detailed_monitoring_enabled'), ('ec2_instance_imdsv2_enabled', 'ec2_instance_imdsv2_enabled'), ('ec2_instance_internet_facing_with_instance_profile', 'ec2_instance_internet_facing_with_instance_profile'), ('ec2_instance_managed_by_ssm', 'ec2_instance_managed_by_ssm'), ('ec2_instance_older_than_specific_days', 'ec2_instance_older_than_specific_days'), ('ec2_instance_profile_attached', 'ec2_instance_profile_attached'), ('ec2_instance_public_ip', 'ec2_instance_public_ip'), ('ec2_instance_secrets_user_data', 'ec2_instance_secrets_user_data'), ('ec2_networkacl_allow_ingress_tcp_port_22', 'ec2_networkacl_allow_ingress_tcp_port_22'), ('ec2_securitygroup_allow_ingress_port_20_21', 'ec2_securitygroup_allow_ingress_port_20_21'), ('ec2_securitygroup_allow_ingress_tcp_port_mysql', 'ec2_securitygroup_allow_ingress_tcp_port_mysql'), ('ec2_securitygroup_allow_wide_open_public_ipv4', 'ec2_securitygroup_allow_wide_open_public_ipv4'), ('ec2_securitygroup_default_restrict_traffic', 'ec2_securitygroup_default_restrict_traffic'), ('ec2_securitygroup_not_used', 'ec2_securitygroup_not_used')], enum_class=ec2.models.EC2ENUM, max_length=50),
        ),
    ]
