# Generated by Django 4.2.6 on 2023-11-13 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_enum_choices.choice_builders
import django_enum_choices.fields
import django_enumfield.db.fields
import rds.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RDS',
            fields=[
                ('rds_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('last_modified', models.DateTimeField()),
                ('passed_num', models.IntegerField()),
                ('total_num', models.IntegerField()),
                ('root_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RDSList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_name', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[("('rds_check_subnet_availability', <IMPORTANCE.HIGH: 0>, 'RDS 서브넷 그룹 내 불필요한 가용 영역이 존재하지 않습니다.')", "('rds_check_subnet_availability', <IMPORTANCE.HIGH: 0>, 'RDS 서브넷 그룹 내 불필요한 가용 영역이 존재하지 않습니다.')"), ("('rds_check_encryption', <IMPORTANCE.MID: 1>, 'RDS 데이터베이스 암호화가 비활성화되어 있습니다.')", "('rds_check_encryption', <IMPORTANCE.MID: 1>, 'RDS 데이터베이스 암호화가 비활성화되어 있습니다.')"), ("('rds_check_logging', <IMPORTANCE.MID: 1>, 'CloudWatch 로그 스트림으로 보관하고 있습니다.')", "('rds_check_logging', <IMPORTANCE.MID: 1>, 'CloudWatch 로그 스트림으로 보관하고 있습니다.')"), ("('rds_check_public_access', <IMPORTANCE.MID: 1>, 'RDS에 대해 Public Access가 허용되어 있지 않습니다.')", "('rds_check_public_access', <IMPORTANCE.MID: 1>, 'RDS에 대해 Public Access가 허용되어 있지 않습니다.')"), ("('db_creation_deletion_privileges', <IMPORTANCE.MID: 1>, 'DBE만 데이터베이스 생성/삭제를 할 수 있도록 설정되어 있습니다.')", "('db_creation_deletion_privileges', <IMPORTANCE.MID: 1>, 'DBE만 데이터베이스 생성/삭제를 할 수 있도록 설정되어 있습니다.')")], enum_class=rds.models.RdsEnum, max_length=97)),
                ('check_code', models.CharField(max_length=255)),
                ('importance', django_enumfield.db.fields.EnumField(default=1, enum=rds.models.IMPORTANCE)),
                ('status', models.BooleanField()),
                ('pass_line', models.TextField()),
                ('check_point', models.TextField()),
                ('modified_date', models.DateTimeField()),
                ('rds_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rds_list_entries', to='rds.rds')),
                ('root_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rds_list_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
