# Generated by Django 4.2.6 on 2023-11-16 18:38

from django.db import migrations
import django_enum_choices.choice_builders
import django_enum_choices.fields
import rds.models


class Migration(migrations.Migration):

    dependencies = [
        ('rds', '0003_alter_rdslist_check_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdslist',
            name='check_name',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('rds_check_rds_subnet_availability', 'rds_check_rds_subnet_availability'), ('rds_check_rds_encryption', 'rds_check_rds_encryption'), ('rds_check_rds_logging', 'rds_check_rds_logging'), ('rds_check_rds_public_access', 'rds_check_rds_public_access'), ('rds_check_db_creation_deletion_privileges', 'rds_check_db_creation_deletion_privileges')], enum_class=rds.models.RdsEnum, max_length=41),
        ),
    ]
